---
- hosts: all
  become: True

  vars:
    pip_install_packages:
      - name: pip
        state: latest
      - name: ansible

  roles:
    - role: geerlingguy.repo-epel
    - role: geerlingguy.pip
